
// Generated by the FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///     await Firebase.initializeApp(
///       options: DefaultFirebaseOptions.currentPlatform,
///     );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // El resto de las plataformas no están configuradas.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - ' 
          'you can run `flutterfire configure` to generate them.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - ' 
          'you can run `flutterfire configure` to generate them.',
        );
       case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - ' 
          'you can run `flutterfire configure` to generate them.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - ' 
          'you can run `flutterfire configure` to generate them.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - ' 
          'you can run `flutterfire configure` to generate them.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAehjLpZLbPeXrT2j5fKcf8Cr4cT46asfY',
    authDomain: 'meteorolocal.firebaseapp.com',
    databaseURL: 'https://meteorolocal-default-rtdb.firebaseio.com',
    projectId: 'meteorolocal',
    storageBucket: 'meteorolocal.firebasestorage.app',
    messagingSenderId: '114922106616',
    appId: '1:114922106616:web:c5fb7a1c04e46f39f8150d',
  );
}
